M48
; DRILL file {KiCad 8.0.3} date 2026-04-22T09:35:08-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-22T09:35:08-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1358
%
G90
G05
T1
X6.4234Y-4.9875
X6.4234Y-5.2631
T2
X5.2483Y-2.3844
X5.5948Y-2.3844
T3
X6.268Y-1.5651
T4
X3.7668Y-1.5651
X5.94Y-2.195
M30
